# Generated by Django 3.2.15 on 2022-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('postDate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=100)),
                ('isInternal', models.CharField(default='Y', max_length=1)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
